import React, { useState } from 'react';
import { Check, Code, Copy, Download, ShieldCheck, X } from 'lucide-react';
import type { FileScanResult } from '../types';

interface AuditReportModalProps { isOpen: boolean; onClose: () => void; results: FileScanResult[]; }

export const AuditReportModal: React.FC<AuditReportModalProps> = ({ isOpen, onClose, results }) => {
  const [copied, setCopied] = useState(false);
  const [tab, setTab] = useState<'summary' | 'json'>('summary');
  if (!isOpen) return null;
  const report = { generated_at: new Date().toISOString(), files: results.map((result) => ({ filename: result.stagedFile.name, baseline: result.baseline, adversarial: result.adversarial, error: result.error })) };
  const json = JSON.stringify(report, null, 2);
  const download = () => { const anchor = document.createElement('a'); anchor.href = `data:application/json;charset=utf-8,${encodeURIComponent(json)}`; anchor.download = 'scanex-response-report.json'; document.body.appendChild(anchor); anchor.click(); anchor.remove(); };
  const copy = () => { void navigator.clipboard?.writeText(json); setCopied(true); window.setTimeout(() => setCopied(false), 1500); };
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-xs"><div className="bg-white border border-[#e7e5e4] rounded-2xl w-full max-w-2xl max-h-[90vh] shadow-xl flex flex-col overflow-hidden"><div className="px-6 py-4 border-b border-[#f0eee9] flex items-center justify-between"><div className="flex items-center gap-2.5"><div className="w-8 h-8 rounded-lg bg-[#e8f5e9] flex items-center justify-center text-[#166534]"><ShieldCheck className="w-5 h-5" /></div><div><h3 className="text-base font-semibold text-[#1f1b17]">ScanEx Response Report</h3><p className="text-xs text-[#717971]">Local export of responses returned in this session</p></div></div><button onClick={onClose} className="p-1.5 text-[#717971] cursor-pointer"><X className="w-4 h-4" /></button></div><div className="px-6 pt-3 flex items-center gap-2 border-b border-[#f5f5f4]"><button onClick={() => setTab('summary')} className={`pb-2 text-xs font-medium border-b-2 ${tab === 'summary' ? 'text-[#316342] border-[#316342]' : 'text-[#717971] border-transparent'}`}>Summary</button><button onClick={() => setTab('json')} className={`pb-2 text-xs font-medium border-b-2 flex items-center gap-1.5 ${tab === 'json' ? 'text-[#316342] border-[#316342]' : 'text-[#717971] border-transparent'}`}><Code className="w-3.5 h-3.5" />JSON</button></div><div className="p-6 overflow-y-auto">{tab === 'summary' ? <div className="space-y-3 text-sm"><p className="text-[#57534e]">{results.length} file response{results.length === 1 ? '' : 's'} captured.</p>{results.map((result) => <div key={result.stagedFile.id} className="border border-[#e7e5e4] rounded-xl p-3"><p className="font-mono font-medium text-[#1f1b17]">{result.stagedFile.name}</p><p className="text-xs text-[#717971]">{result.error || 'Baseline response available'}{result.adversarial ? ' · Adversarial response available' : ''}</p></div>)}</div> : <div className="relative"><pre className="p-4 bg-[#1f1b17] text-[#e2d8d2] font-mono text-[11px] rounded-xl overflow-x-auto max-h-80 leading-relaxed">{json}</pre><button onClick={copy} className="absolute top-3 right-3 px-2.5 py-1 text-xs bg-[#342f2b] text-white rounded-md flex items-center gap-1.5 cursor-pointer">{copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}{copied ? 'Copied' : 'Copy'}</button></div>}</div><div className="px-6 py-4 bg-[#fafaf9] border-t border-[#f0eee9] flex items-center justify-end gap-2"><button onClick={download} className="px-4 py-2 text-xs font-semibold text-white bg-[#316342] rounded-xl flex items-center gap-1.5 cursor-pointer"><Download className="w-3.5 h-3.5" />Download JSON</button><button onClick={onClose} className="px-4 py-2 text-xs font-medium text-[#292524] bg-white border border-[#e7e5e4] rounded-xl cursor-pointer">Close</button></div></div></div>;
};
